// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie.proto
// Protobuf Java Version: 4.29.1

package proto.files;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.Empty)
    com.google.protobuf.MessageOrBuilder {
}
