// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie.proto
// Protobuf Java Version: 4.29.1

package proto.files;

public interface CreateMovieRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.CreateMovieRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string director = 2;</code>
   * @return The director.
   */
  java.lang.String getDirector();
  /**
   * <code>string director = 2;</code>
   * @return The bytes for director.
   */
  com.google.protobuf.ByteString
      getDirectorBytes();

  /**
   * <code>string genre = 3;</code>
   * @return The genre.
   */
  java.lang.String getGenre();
  /**
   * <code>string genre = 3;</code>
   * @return The bytes for genre.
   */
  com.google.protobuf.ByteString
      getGenreBytes();

  /**
   * <code>int32 year = 4;</code>
   * @return The year.
   */
  int getYear();
}
