// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie.proto
// Protobuf Java Version: 4.29.1

package proto.files;

/**
 * Protobuf type {@code movie.GetMovieResponse}
 */
public final class GetMovieResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:movie.GetMovieResponse)
    GetMovieResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GetMovieResponse.class.getName());
  }
  // Use GetMovieResponse.newBuilder() to construct.
  private GetMovieResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetMovieResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.files.MovieServiceProto.internal_static_movie_GetMovieResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.files.MovieServiceProto.internal_static_movie_GetMovieResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.files.GetMovieResponse.class, proto.files.GetMovieResponse.Builder.class);
  }

  private int bitField0_;
  public static final int MOVIE_FIELD_NUMBER = 1;
  private proto.files.Movie movie_;
  /**
   * <code>.movie.Movie movie = 1;</code>
   * @return Whether the movie field is set.
   */
  @java.lang.Override
  public boolean hasMovie() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.movie.Movie movie = 1;</code>
   * @return The movie.
   */
  @java.lang.Override
  public proto.files.Movie getMovie() {
    return movie_ == null ? proto.files.Movie.getDefaultInstance() : movie_;
  }
  /**
   * <code>.movie.Movie movie = 1;</code>
   */
  @java.lang.Override
  public proto.files.MovieOrBuilder getMovieOrBuilder() {
    return movie_ == null ? proto.files.Movie.getDefaultInstance() : movie_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMovie());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMovie());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.files.GetMovieResponse)) {
      return super.equals(obj);
    }
    proto.files.GetMovieResponse other = (proto.files.GetMovieResponse) obj;

    if (hasMovie() != other.hasMovie()) return false;
    if (hasMovie()) {
      if (!getMovie()
          .equals(other.getMovie())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMovie()) {
      hash = (37 * hash) + MOVIE_FIELD_NUMBER;
      hash = (53 * hash) + getMovie().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.files.GetMovieResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.files.GetMovieResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.files.GetMovieResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.files.GetMovieResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.files.GetMovieResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.files.GetMovieResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.files.GetMovieResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.files.GetMovieResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.files.GetMovieResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.files.GetMovieResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.files.GetMovieResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.files.GetMovieResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.files.GetMovieResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code movie.GetMovieResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:movie.GetMovieResponse)
      proto.files.GetMovieResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.files.MovieServiceProto.internal_static_movie_GetMovieResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.files.MovieServiceProto.internal_static_movie_GetMovieResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.files.GetMovieResponse.class, proto.files.GetMovieResponse.Builder.class);
    }

    // Construct using proto.files.GetMovieResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getMovieFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      movie_ = null;
      if (movieBuilder_ != null) {
        movieBuilder_.dispose();
        movieBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.files.MovieServiceProto.internal_static_movie_GetMovieResponse_descriptor;
    }

    @java.lang.Override
    public proto.files.GetMovieResponse getDefaultInstanceForType() {
      return proto.files.GetMovieResponse.getDefaultInstance();
    }

    @java.lang.Override
    public proto.files.GetMovieResponse build() {
      proto.files.GetMovieResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.files.GetMovieResponse buildPartial() {
      proto.files.GetMovieResponse result = new proto.files.GetMovieResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(proto.files.GetMovieResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.movie_ = movieBuilder_ == null
            ? movie_
            : movieBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.files.GetMovieResponse) {
        return mergeFrom((proto.files.GetMovieResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.files.GetMovieResponse other) {
      if (other == proto.files.GetMovieResponse.getDefaultInstance()) return this;
      if (other.hasMovie()) {
        mergeMovie(other.getMovie());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMovieFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private proto.files.Movie movie_;
    private com.google.protobuf.SingleFieldBuilder<
        proto.files.Movie, proto.files.Movie.Builder, proto.files.MovieOrBuilder> movieBuilder_;
    /**
     * <code>.movie.Movie movie = 1;</code>
     * @return Whether the movie field is set.
     */
    public boolean hasMovie() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     * @return The movie.
     */
    public proto.files.Movie getMovie() {
      if (movieBuilder_ == null) {
        return movie_ == null ? proto.files.Movie.getDefaultInstance() : movie_;
      } else {
        return movieBuilder_.getMessage();
      }
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     */
    public Builder setMovie(proto.files.Movie value) {
      if (movieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        movie_ = value;
      } else {
        movieBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     */
    public Builder setMovie(
        proto.files.Movie.Builder builderForValue) {
      if (movieBuilder_ == null) {
        movie_ = builderForValue.build();
      } else {
        movieBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     */
    public Builder mergeMovie(proto.files.Movie value) {
      if (movieBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          movie_ != null &&
          movie_ != proto.files.Movie.getDefaultInstance()) {
          getMovieBuilder().mergeFrom(value);
        } else {
          movie_ = value;
        }
      } else {
        movieBuilder_.mergeFrom(value);
      }
      if (movie_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     */
    public Builder clearMovie() {
      bitField0_ = (bitField0_ & ~0x00000001);
      movie_ = null;
      if (movieBuilder_ != null) {
        movieBuilder_.dispose();
        movieBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     */
    public proto.files.Movie.Builder getMovieBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMovieFieldBuilder().getBuilder();
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     */
    public proto.files.MovieOrBuilder getMovieOrBuilder() {
      if (movieBuilder_ != null) {
        return movieBuilder_.getMessageOrBuilder();
      } else {
        return movie_ == null ?
            proto.files.Movie.getDefaultInstance() : movie_;
      }
    }
    /**
     * <code>.movie.Movie movie = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        proto.files.Movie, proto.files.Movie.Builder, proto.files.MovieOrBuilder> 
        getMovieFieldBuilder() {
      if (movieBuilder_ == null) {
        movieBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            proto.files.Movie, proto.files.Movie.Builder, proto.files.MovieOrBuilder>(
                getMovie(),
                getParentForChildren(),
                isClean());
        movie_ = null;
      }
      return movieBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:movie.GetMovieResponse)
  }

  // @@protoc_insertion_point(class_scope:movie.GetMovieResponse)
  private static final proto.files.GetMovieResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.files.GetMovieResponse();
  }

  public static proto.files.GetMovieResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMovieResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetMovieResponse>() {
    @java.lang.Override
    public GetMovieResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetMovieResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetMovieResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.files.GetMovieResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

