// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie.proto
// Protobuf Java Version: 4.29.1

package proto.files;

public interface GetMovieResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.GetMovieResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.movie.Movie movie = 1;</code>
   * @return Whether the movie field is set.
   */
  boolean hasMovie();
  /**
   * <code>.movie.Movie movie = 1;</code>
   * @return The movie.
   */
  proto.files.Movie getMovie();
  /**
   * <code>.movie.Movie movie = 1;</code>
   */
  proto.files.MovieOrBuilder getMovieOrBuilder();
}
